baseurl: https://botam2.github.io/workshop/
copyright: Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved.
paginate: 10
theme: hugo-clarity
disqusShortname: ''
DefaultContentLanguage: en
taxonomies:
  category: categories
  series: series
  tag: tags
