baseurl: https://epi-rgee.netlify.app/
copyright: Copyright © 2021, Antony Barja. Todo los derechos reservados
paginate: 10
theme: hugo-clarity
disqusShortname: ''
DefaultContentLanguage: en
taxonomies:
  tag: tags
