[[main]]
  name = "Home"
  url = "post/"
  weight = -110

[[main]]
  name = "Installation"
  url = "installation/"
  weight = -109

[[main]]
  name = "Demos"
  url = "demos/"
  weight = -108



# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -107
[[main]]
  parent = "Links"
  name = "rgee"
  url = ""
[[main]]
  parent = "Links"
  name = "rgeeExtra"
  url = ""

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/#"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/#"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/#"

[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"