
<!DOCTYPE html>
<html lang="en" data-figures="true" class="page" data-mode="lit">
  <head>
<title>Introdução ao framework {mlr3} | Datamares &amp; Dreamscapes</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<script async src="https://www.googletagmanager.com/gtag/js?id=G-B65R9LH9ES"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-B65R9LH9ES');
</script>
  
<meta property="og:locale" content="en" />

<meta property="og:type" content="article">
<meta name="description" content="Uma introdução ao framework de machine learning mlr3, um pacote de R.">
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:creator" content="@AlbersonMiranda">
<meta name="twitter:title" content="Introdução ao framework {mlr3}" />
<meta property="og:url" content="https://botam2.github.io/workshop/post/2020-11-29-introducao-ao-mlr3-framework/" />
<meta property="og:title" content="Introdução ao framework {mlr3}" />
<meta property="og:description" content="Uma introdução ao framework de machine learning mlr3, um pacote de R." />
<meta property="og:image" content="https://botam2.github.io/workshop/images/posts/2020-12-20%20-%20intro-mlr3.jpeg" />

<link rel="apple-touch-icon" sizes="180x180" href="https://botam2.github.io/workshop/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="https://botam2.github.io/workshop/icons/favicon-32x32.png">
<link rel="manifest" href="https://botam2.github.io/workshop/icons/site.webmanifest">

<link rel="canonical" href="https://botam2.github.io/workshop/post/2020-11-29-introducao-ao-mlr3-framework/">

    

    
    
    <link rel="preload" href="https://botam2.github.io/workshop/css/styles.14408e7a6e0114330a9aa434e0c3b0a757cd9c984944cb9b444d45ce8f0af2be87dea13ebcb30b98e6626d59c738f951faabbd45a1ce8d91b6d4428d2d86b254.css" integrity = "sha512-FECOem4BFDMKmqQ04MOwp1fNnJhJRMubRE1Fzo8K8r6H3qE&#43;vLMLmOZibVnHOPlR&#43;qu9RaHOjZG21EKNLYayVA==" as="style" crossorigin="anonymous">
    <link rel="preload" href="https://botam2.github.io/workshop/js/bundle.min.d14fbcd65c3ba32e60cab81f8bbe7aa9b7f8b95ff8290e437fb26ff9ab7f7ea0c928db2dca60aac91f192db906f2d90678f83907e4e3994f6ff9fdb5bdea3369.js" as="script" integrity=
    "sha512-0U&#43;81lw7oy5gyrgfi756qbf4uV/4KQ5Df7Jv&#43;at/fqDJKNstymCqyR8ZLbkG8tkGePg5B&#43;TjmU9v&#43;f21veozaQ==" crossorigin="anonymous">

    
    <link rel="stylesheet" type="text/css" href="https://botam2.github.io/workshop/css/styles.14408e7a6e0114330a9aa434e0c3b0a757cd9c984944cb9b444d45ce8f0af2be87dea13ebcb30b98e6626d59c738f951faabbd45a1ce8d91b6d4428d2d86b254.css" integrity="sha512-FECOem4BFDMKmqQ04MOwp1fNnJhJRMubRE1Fzo8K8r6H3qE&#43;vLMLmOZibVnHOPlR&#43;qu9RaHOjZG21EKNLYayVA==" crossorigin="anonymous">
    
  </head>
  
  
  
    
  
  <body data-code="10" data-lines="true" id="documentTop">

<header class="nav_header" >
  <nav class="nav"><a href='https://botam2.github.io/workshop/' class="nav_brand nav_item" title="Datamares &amp; Dreamscapes">
  <img src="https://botam2.github.io/workshop/logos/logo.png" class="logo" alt="Datamares &amp; Dreamscapes">
  <div class="nav_close">
    <div><svg class="icon">
  <use xlink:href="#open-menu"></use>
</svg><svg class="icon">
  <use xlink:href="#closeme"></use>
</svg></div>
  </div>
</a>

    <div class='nav_body nav_body_right'>
      
      
      
        

  <div class="nav_parent">
    <a href="https://botam2.github.io/workshop/" class="nav_item" title="Home">Home </a>
  </div>
  <div class="nav_parent">
    <a href="https://botam2.github.io/workshop/post/" class="nav_item" title="Archives">Archives </a>
  </div>
  <div class="nav_parent">
    <a href="https://botam2.github.io/workshop/" class="nav_item" title="Links">Links <img src='https://botam2.github.io/workshop/icons/caret-icon.svg' alt="icon" class="nav_icon"></a>
    <div class="nav_sub">
      <span class="nav_child"></span>
        <a href="https://datamares.netlify.app/files/cv.pdf" class="nav_child nav_item" title="Curriculum Vitae">Curriculum Vitae</a>
    </div>
  </div>
  <div class="nav_parent">
    <a href="https://botam2.github.io/workshop/about/" class="nav_item" title="About">About </a>
  </div>
      
      <div class="nav_parent">
        <a href="#" class="nav_item">lang 🌐</a>
        <div class="nav_sub">
          <span class="nav_child"></span>
          
          <a href="https://botam2.github.io/workshop/" class="nav_child nav_item">English</a>
          
          <a href="https://botam2.github.io/workshop/pt/" class="nav_child nav_item">Português</a>
          
        </div>
      </div>
<div class='follow'>
  <a href="https://github.com/albersonmiranda">
    <svg class="icon">
  <use xlink:href="#github"></use>
</svg>
  </a>
  <a href="https://twitter.com/AlbersonMiranda">
    <svg class="icon">
  <use xlink:href="#twitter"></use>
</svg>
  </a>
  <a href="https://www.facebook.com/alberson.miranda">
    <svg class="icon">
  <use xlink:href="#facebook"></use>
</svg>
  </a>
  <a href="https://gitlab.com/albersonmiranda">
    <svg class="icon">
  <use xlink:href="#gitlab"></use>
</svg>
  </a>
  <a href="https://www.instagram.com/alberson.miranda/">
    <svg class="icon">
  <use xlink:href="#instagram"></use>
</svg>
  </a>
  <a href="https://www.linkedin.com/in/albersonmiranda/">
    <svg class="icon">
  <use xlink:href="#linkedin"></use>
</svg>
  </a>
  <a href="https://stackoverflow.com/users/8430277/alberson-miranda">
    <svg class="icon">
  <use xlink:href="#stackoverflow"></use>
</svg>
  </a>
<div class="color_mode">
  <input type="checkbox" class="color_choice" id="mode">
</div>

</div>

    </div>
  </nav>
</header>

    <main>
  
<div class="grid-inverse wrap content">
  <article class="post_content">
    <h1 class="post_title">Introdução ao framework {mlr3}</h1>
  <div class="post_meta">
    <span><svg class="icon">
  <use xlink:href="#calendar"></use>
</svg></span>
    <span class="post_date">
      Dec 27, 2020</span>
    <span class="post_time"> · 13 min read</span><span>&nbsp;· <a href='https://botam2.github.io/workshop/tags/mlr3' title="mlr3" class="post_tag button button_translucent">mlr3
        </a><a href='https://botam2.github.io/workshop/tags/r' title="R" class="post_tag button button_translucent">R
        </a>
    </span>
    <span class="page_only">&nbsp;·
  <div class="post_share">
    Share on:
    <a href="https://twitter.com/intent/tweet?text=Introdu%c3%a7%c3%a3o%20ao%20framework%20%7bmlr3%7d&url=https%3a%2f%2fbotam2.github.io%2fworkshop%2fpost%2f2020-11-29-introducao-ao-mlr3-framework%2f&tw_p=tweetbutton" class="twitter" title="Share on Twitter" target="_blank" rel="nofollow">
      <svg class="icon">
  <use xlink:href="#twitter"></use>
</svg>
    </a>
    <a href="https://www.facebook.com/sharer.php?u=https%3a%2f%2fbotam2.github.io%2fworkshop%2fpost%2f2020-11-29-introducao-ao-mlr3-framework%2f&t=Introdu%c3%a7%c3%a3o%20ao%20framework%20%7bmlr3%7d" class="facebook" title="Share on Facebook" target="_blank" rel="nofollow">
      <svg class="icon">
  <use xlink:href="#facebook"></use>
</svg>
    </a>
    <a href="#linkedinshare" id = "linkedinshare" class="linkedin" title="Share on LinkedIn" rel="nofollow">
      <svg class="icon">
  <use xlink:href="#linkedin"></use>
</svg>
    </a>
    <a href="https://botam2.github.io/workshop/post/2020-11-29-introducao-ao-mlr3-framework/" title="Copy Link" class="link link_yank">
      <svg class="icon">
  <use xlink:href="#copy"></use>
</svg>
    </a>
  </div>
  </span>
  </div>

    
    <img src="img/mlr3verse.svg" class="image_featured" alt="Introdução ao framework {mlr3}">
    
    
<script src="https://botam2.github.io/workshop/post/2020-11-29-introducao-ao-mlr3-framework/index_files/header-attrs/header-attrs.js"></script>


<p>Esse é o primeiro post de uma série que irá tratar sobre o ecossistema {mlr3} <span class="citation">(<a href="#ref-mlr3" role="doc-biblioref">Lang et al. 2019</a>)</span>. Ele é mais completo e também muito mais complexo do que seu predecessor, o {mlr}, que teve sua versão inicial publicada no CRAN em 2013. O ecossistema permite um framework agnóstico (i.e. não depende dos algoritmos escolhidos), extensível e orientado a objeto, e, atualmente, permite vários tipos de tarefas, como classificação, regressão, análise de sobrevivência, forecasting, clustering, dentre outros. O {mlr3} tem diversas vantagens que o faz, IMHO, o <em>framework</em> mais completo para se trabalhar <em>machine learning</em> em R <span class="citation">(<a href="#ref-R" role="doc-biblioref">R Core Team 2020</a>)</span> e elas ficarão claras ao longo dos próximos posts.</p>
<div id="introdução" class="section level1">
<h1>INTRODUÇÃO</h1>
<p>O workflow padrão de um projeto de machine learning consiste em:</p>
<ol style="list-style-type: decimal">
<li>dividir sua amostra em treino e teste (<em>split</em>);</li>
<li>escolher o algoritmo<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> apropriado para o tipo de tarefa;</li>
<li>passar a amostra de treino ao algoritmo para criar um modelo do relacionamento entre a variável de resposta (<em>output features</em>) e as explicativas (<em>input features</em>);</li>
<li>passar os dados de testes ao modelo treinado para produzir predições;</li>
<li>comparar as predições com os dados da amostra;</li>
<li>mensurar a performance do modelo através de medidas de acurácia estabelecidas.</li>
</ol>
<p><img src="img/basics.svg" /></p>
<p>O processo de repetir esse workflow várias vezes, separando a amostra treino em várias partes diferentes e usando outras como <em>fake test samples</em> é chamado de <em>resampling</em>, um processo vital para a etapa de calibragem e para evitar o <em>overfitting</em>.</p>
<p>Dependendo dos dados, do tipo de tarefa e algoritmo escolhido, podem ser necessários vários filtros, como normalização, <em>feature selection</em> e tratamento de <em>outliers</em> ou dados faltantes. Para esses casos, o {mlr3} tem novas soluções que se destacam com muita vantagem em relação não só ao seu predecessor {mlr} como também a outros <em>frameworks</em> de <em>machine learning</em> em R, como o {caret} e o {tidymodels}.</p>
<div id="características-de-design" class="section level2">
<h2>CARACTERÍSTICAS DE DESIGN</h2>
<p>Alguns princípios gerais que norteiam o desenvolvimento do pacote e afetam muito seu uso são:</p>
<ul>
<li><p>Foco no <em>backend</em>. A maioria dos pacotes do ecossistema tem objetivo de processar e transformar dados, aplicar algoritmos e computar resultados. Visualizações são providenciadas em pacotes externos;</p></li>
<li><p>Adoção da classe R6 <span class="citation">(<a href="#ref-R-R6" role="doc-biblioref">Chang 2020</a>)</span> para design orientado a objeto, <em>modify-in-place</em> e semântica de referência (falaremos um pouco sobre esses conceitos adiante);</p></li>
<li><p>Adoção do {data.table} <span class="citation">(<a href="#ref-R-data.table" role="doc-biblioref">Dowle and Srinivasan 2020</a>)</span> para manipulações de <em>data frames</em>. A combinação {R6} + {data.table} torna a performance um dos pontos fortes do ecossistema.</p></li>
<li><p>Baixa dependência. Entretanto, os algortimos não são implementados no ecossistema, como no scikit-learn em Python. Para executar o XGBoost <span class="citation">(<a href="#ref-xgboost" role="doc-biblioref">Chen et al. 2020</a>)</span>, por exemplo, deve-se ter instalado o pacote que o implementa.</p></li>
</ul>
</div>
<div id="fora-do-escopo" class="section level2">
<h2>FORA DO ESCOPO</h2>
<p>Como se trata de uma introdução, as etapas de <em>tunning</em> e <em>resampling</em>, assim como funcionalidades como os <em>pipelines</em>, serão abordadas em postagens futuras. Neste post trataremos apenas os conceitos básicos do <em>workflow</em>.</p>
</div>
</div>
<div id="direto-ao-ponto" class="section level1">
<h1>DIRETO AO PONTO</h1>
<p>Para conhecer as funcionalidades básicas do pacote, usaremos um dos <em>datasets</em> inclusos no R, o <code>swiss</code>. Esse <em>dataset</em> consiste na medição padronizada da fertilidade e indicadores socioeconômicos de 47 províncias da Suíça em 1888.</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln">1</span><span class="c1"># criando dataframe</span>
<span class="ln">2</span><span class="n">data</span> <span class="o">=</span> <span class="n">swiss</span>
<span class="ln">3</span>
<span class="ln">4</span><span class="c1"># overview</span>
<span class="ln">5</span><span class="n">skimr</span><span class="o">::</span><span class="nf">skim</span><span class="p">(</span><span class="n">data</span><span class="p">)</span></code></pre></div>
<table>
<caption><span id="tab:data">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">47</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">6</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">6</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Fertility</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">70.14</td>
<td align="right">12.49</td>
<td align="right">35.00</td>
<td align="right">64.70</td>
<td align="right">70.40</td>
<td align="right">78.45</td>
<td align="right">92.5</td>
<td align="left">▂▂▇▇▅</td>
</tr>
<tr class="even">
<td align="left">Agriculture</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">50.66</td>
<td align="right">22.71</td>
<td align="right">1.20</td>
<td align="right">35.90</td>
<td align="right">54.10</td>
<td align="right">67.65</td>
<td align="right">89.7</td>
<td align="left">▃▃▆▇▅</td>
</tr>
<tr class="odd">
<td align="left">Examination</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">16.49</td>
<td align="right">7.98</td>
<td align="right">3.00</td>
<td align="right">12.00</td>
<td align="right">16.00</td>
<td align="right">22.00</td>
<td align="right">37.0</td>
<td align="left">▅▇▆▂▂</td>
</tr>
<tr class="even">
<td align="left">Education</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">10.98</td>
<td align="right">9.62</td>
<td align="right">1.00</td>
<td align="right">6.00</td>
<td align="right">8.00</td>
<td align="right">12.00</td>
<td align="right">53.0</td>
<td align="left">▇▃▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">Catholic</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">41.14</td>
<td align="right">41.70</td>
<td align="right">2.15</td>
<td align="right">5.20</td>
<td align="right">15.14</td>
<td align="right">93.12</td>
<td align="right">100.0</td>
<td align="left">▇▁▁▁▅</td>
</tr>
<tr class="even">
<td align="left">Infant.Mortality</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">19.94</td>
<td align="right">2.91</td>
<td align="right">10.80</td>
<td align="right">18.15</td>
<td align="right">20.00</td>
<td align="right">21.70</td>
<td align="right">26.6</td>
<td align="left">▁▂▇▆▂</td>
</tr>
</tbody>
</table>
<p>Dentre as vari]]áveis disponíveis, podemos escolher modelar a mortalidade infantil <code>Infant.Mortality</code> baseada nas demais features, que são:</p>
<ul>
<li><code>Fertility</code>: Medida de fertilidade. Assim como a mortalidade infantil, está escalonada entre 0-100.</li>
<li><code>Agriculture</code>: Percentual de homens envolvidos em agricultura como ocupação.</li>
<li><code>Examination</code>: Percentual de alistados bem avaliados nos exames do exército.</li>
<li><code>Education</code>: Percentual dos alistados com educação superior ao primário.</li>
<li><code>Catholic</code>: Percentual de católicos (em oposto a protestantes).</li>
</ul>
<p>O <em>workflow</em> começa pela criação da <code>task</code>, que é um objeto que contém os dados e informações sobre a tarefa a ser executada, como a variável de resposta<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> e as demais <em>features</em>, além de seus tipos. Como queremos realizar predições para uma variável numérica contínua, é uma tarefa de regressão.</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln">1</span><span class="c1"># importando pacote</span>
<span class="ln">2</span><span class="nf">library</span><span class="p">(</span><span class="n">mlr3verse</span><span class="p">)</span>
<span class="ln">3</span>
<span class="ln">4</span><span class="c1"># criando task</span>
<span class="ln">5</span><span class="n">task_swiss</span> <span class="o">=</span> <span class="n">TaskRegr</span><span class="o">$</span><span class="nf">new</span><span class="p">(</span>
<span class="ln">6</span>  <span class="n">id</span> <span class="o">=</span> <span class="s">&#34;swiss&#34;</span><span class="p">,</span>
<span class="ln">7</span>  <span class="n">backend</span> <span class="o">=</span> <span class="n">data</span><span class="p">,</span>
<span class="ln">8</span>  <span class="n">target</span> <span class="o">=</span> <span class="s">&#34;Infant.Mortality&#34;</span>
<span class="ln">9</span><span class="p">)</span></code></pre></div>
<p>Notou algo estranho? Como o {mlr3} trabalha com a classe R6, seu manuseio é mais parecido com outras linguagens orientadas a objeto, como o Python. Essa classe tem duas propriedades especiais:</p>
<ul>
<li><p>Métodos pertencem a objetos e são chamados na forma <code>objeto$metodo()</code> e não como funções genéricas como <code>foo()</code>. Esse é o paradigma OOP (programação orientada à objetos). No caso acima, não há uma função para criar uma <em>task</em> como <code>task_regr_new()</code>, mas um método <code>new()</code> associado ao objeto <code>TaskRegr</code>;</p></li>
<li><p>Os objetos da classe R6 são mutáveis, ou seja, eles são modificados no local (<em>modify-in-place</em>) e, portanto, têm semântica de referência. Isso significa que eles não são copiados a cada modificação, como os <em>data frames</em> comuns (classe S3), o que é um fator de alocação de memória e, consequentemente, lentidão.</p></li>
</ul>
<p>O efeito colateral é que isso não é muito familiar para pessoas que não conhecem outras linguagens de programação além do R e no início pode parecer pouco natural e confuso.</p>
<p>Criado o objeto, podemos acessá-lo para verificar e visualizar as informações ali contidas:</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln">1</span><span class="c1"># verificando</span>
<span class="ln">2</span><span class="n">task_swiss</span>
<span class="ln">3</span>
<span class="ln">4</span><span class="c1"># visualizando</span>
<span class="ln">5</span><span class="nf">autoplot</span><span class="p">(</span><span class="n">task_swiss</span><span class="p">,</span> <span class="n">type</span> <span class="o">=</span> <span class="s">&#34;pairs&#34;</span><span class="p">)</span></code></pre></div>
<pre><code>## &lt;TaskRegr:swiss&gt; (47 x 6)
## * Target: Infant.Mortality
## * Properties: -
## * Features (5):
##   - dbl (3): Agriculture, Catholic, Fertility
##   - int (2): Education, Examination</code></pre>
<p><img src="https://botam2.github.io/workshop/post/2020-11-29-introducao-ao-mlr3-framework/index_files/figure-html/task_cont-1.png" width="672" /></p>
<p>Podemos ver que apenas a fertilidade é linearmente correlacionada com a mortalidade infantil — quanto maior a fertilidade, maior a mortalidade —, e podemos esperar que tenha maior peso nas predições. As demais variáveis não apresentam correlação linear significativa com a variável de resposta. Entretanto, apresentam correlação moderada ou forte entre si, mas não a ponto de apresentar colinearidade, o que demandaria tratamento.</p>
<p>Agora selecionamos o algoritmo<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> que será usado para treinar o modelo. Escolhi aqui o <em>XGBoost</em>. A lista completa pode ser acessada <a href="https://mlr3extralearners.mlr-org.com/articles/learners/learner_status.html">por essa lista estática</a>, <a href="https://mlr3extralearners.mlr-org.com/articles/learners/list_learners.html">por essa lista dinâmica</a> ou pela função <code>mlr3extralearners::list_mlr3learners()</code>. Como mencionado anteriormente, os algoritmos não são implementados pelo ecossistema do {mlr3} e nas listas citadas constam os pacotes onde os algoritmos foram implementados e que devem ser baixados para o seu uso.</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln">1</span><span class="c1"># definindo o learner</span>
<span class="ln">2</span><span class="n">l_xgboost</span> <span class="o">=</span> <span class="nf">lrn</span><span class="p">(</span><span class="s">&#34;regr.xgboost&#34;</span><span class="p">)</span>
<span class="ln">3</span>
<span class="ln">4</span><span class="c1"># checando</span>
<span class="ln">5</span><span class="n">l_xgboost</span></code></pre></div>
<pre><code>## &lt;LearnerRegrXgboost:regr.xgboost&gt;
## * Model: -
## * Parameters: nrounds=1, nthread=1, verbose=0
## * Packages: xgboost
## * Predict Type: response
## * Feature types: logical, integer, numeric
## * Properties: importance, missings, weights</code></pre>
<p>Vamos entender o que o objeto <code>l_xgboost</code> nos diz.</p>
<ol style="list-style-type: decimal">
<li><strong>Model</strong>: Vazio, pois ainda não há um modelo treinado;</li>
<li><strong>Parameters</strong>: Os hiperparâmetros a serem escolhidos e tunados para performance do modelo;</li>
<li><strong>Packages</strong>: O pacote onde o algorítmo foi implementado e de onde será importado pelo {mlr3};</li>
<li><strong>Predict Type</strong>: Se <code>response</code> a predição é retornada como 0 ou 1, no caso de classificação, ou num valor para variável de resposta, no caso de regressão — neste caso, será a mortalidade infantil escalonada no intervalo [1, 100]. Se “prob,” para classificação, a predição retorna a probabilidade entre 0 e 1;</li>
<li><strong>Feature Type</strong>: Os tipos de variáveis que o algoritmo é capaz de manipular. No caso do <em>XGBoost</em>, por exemplo, apenas variáveis numéricas podem ser utilizadas. Isso quer dizer que os fatores devem ser convertidos em valores binários (i.e. 0 ou 1), ou seja, deve-se tornar a matriz esparsa — no caso de um fator <code>sexo</code>, por exemplo, na fase de pre-processamento seriam criadas as colunas <code>sexo.masculino</code>, com valores de 1 ou 0, e <code>sexo.feminino</code>, também com 1 ou 0;</li>
<li><strong>Properties</strong>: Propriedades e capacidades adicionais do algoritmo. Neste caso, o <strong>XGBoost</strong> possui a capacidade de computar e retornar os valores da importância das <em>features</em> para o modelo; a capacidade de trabalhar com dados faltantes (<em>missings</em>); a capacidade de computar e retornar os pesos associados às <em>features</em>.</li>
</ol>
<p>Como pode ver em <em>parameters</em>, não há nenhum hiperparâmetro configurado. Podemos acessá-los da seguinte maneira:</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln">1</span><span class="c1"># acessando hiperparâmetros</span>
<span class="ln">2</span><span class="nf">head</span><span class="p">(</span><span class="nf">as.data.table</span><span class="p">(</span><span class="n">l_xgboost</span><span class="o">$</span><span class="n">param_set</span><span class="p">))</span></code></pre></div>
<pre><code>##                  id    class lower upper               levels nlevels
## 1:          booster ParamFct    NA    NA gbtree,gblinear,dart       3
## 2:        watchlist ParamUty    NA    NA                          Inf
## 3:              eta ParamDbl     0     1                          Inf
## 4:            gamma ParamDbl     0   Inf                          Inf
## 5:        max_depth ParamInt     0   Inf                          Inf
## 6: min_child_weight ParamDbl     0   Inf                          Inf
##    is_bounded special_vals default storage_type  tags
## 1:       TRUE    &lt;list[0]&gt;  gbtree    character train
## 2:      FALSE    &lt;list[0]&gt;                 list train
## 3:       TRUE    &lt;list[0]&gt;     0.3      numeric train
## 4:      FALSE    &lt;list[0]&gt;       0      numeric train
## 5:      FALSE    &lt;list[0]&gt;       6      integer train
## 6:      FALSE    &lt;list[0]&gt;       1      numeric train</code></pre>
<p>Como o <em>tunning</em> de hiperparâmetros não é o assunto, vamos apenas configurar algumas coisas básicas para demonstrar como essas informações são acessadas e modificadas. O método para isso é o <code>param_set$values</code>:</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln"> 1</span><span class="c1"># hiperparâmetros</span>
<span class="ln"> 2</span><span class="n">l_xgboost</span><span class="o">$</span><span class="n">param_set</span><span class="o">$</span><span class="n">values</span> <span class="o">=</span> <span class="nf">list</span><span class="p">(</span>
<span class="ln"> 3</span>  <span class="c1"># mandando o algoritmo parar depois de 10 iterações sem melhora no score</span>
<span class="ln"> 4</span>  <span class="n">early_stopping_rounds</span> <span class="o">=</span> <span class="m">10</span><span class="p">,</span>
<span class="ln"> 5</span>  <span class="c1"># mandando o algoritmo treinar mais lentamente</span>
<span class="ln"> 6</span>  <span class="n">eta</span> <span class="o">=</span> <span class="m">0.1</span><span class="p">,</span>
<span class="ln"> 7</span>  <span class="c1"># limitando profundidade da árvore</span>
<span class="ln"> 8</span>  <span class="n">max_depth</span> <span class="o">=</span> <span class="m">5</span><span class="p">,</span>
<span class="ln"> 9</span>  <span class="c1"># quantidade máxima de iterações</span>
<span class="ln">10</span>  <span class="n">nrounds</span> <span class="o">=</span> <span class="m">100</span>
<span class="ln">11</span><span class="p">)</span>
<span class="ln">12</span>
<span class="ln">13</span><span class="c1"># verificando</span>
<span class="ln">14</span><span class="n">l_xgboost</span></code></pre></div>
<pre><code>## &lt;LearnerRegrXgboost:regr.xgboost&gt;
## * Model: -
## * Parameters: early_stopping_rounds=10, eta=0.1, max_depth=5,
##   nrounds=100
## * Packages: xgboost
## * Predict Type: response
## * Feature types: logical, integer, numeric
## * Properties: importance, missings, weights</code></pre>
</div>
<div id="treino-e-predição" class="section level1">
<h1>TREINO E PREDIÇÃO</h1>
<p>As próximas etapas são o treino e a predição — trataremos de <em>tunning</em> e <em>resampling</em> nos próximos posts. Primeiramente, o <em>split</em> do dataset em treino e teste. Para isso, usaremos a função <code>sample()</code> em dois métodos do objeto <code>task_swiss</code>, o <code>row_ids</code> e <code>nrow</code>. O primeiro enumera os índices de cada linha:</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln">1</span><span class="c1"># método row_ids</span>
<span class="ln">2</span><span class="n">task_swiss</span><span class="o">$</span><span class="n">row_ids</span></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
## [26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47</code></pre>
<p>Enquanto o segundo retorna a quantidade de linhas do dataset:</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln">1</span><span class="c1"># método row_ids</span>
<span class="ln">2</span><span class="n">task_swiss</span><span class="o">$</span><span class="n">nrow</span></code></pre></div>
<pre><code>## [1] 47</code></pre>
<p>Assim, podemos selecionar os índice do dataset em duas amostras aleatórias:</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln"> 1</span><span class="c1"># garantindo reprodutibilidade</span>
<span class="ln"> 2</span><span class="nf">set.seed</span><span class="p">(</span><span class="m">1</span><span class="p">)</span>
<span class="ln"> 3</span>
<span class="ln"> 4</span><span class="c1"># índices para amostra treino</span>
<span class="ln"> 5</span><span class="n">train_set</span> <span class="o">=</span> <span class="nf">sample</span><span class="p">(</span><span class="n">task_swiss</span><span class="o">$</span><span class="n">row_ids</span><span class="p">,</span> <span class="m">0.7</span> <span class="o">*</span> <span class="n">task_swiss</span><span class="o">$</span><span class="n">nrow</span><span class="p">)</span>
<span class="ln"> 6</span>
<span class="ln"> 7</span><span class="c1"># índices para amostra teste</span>
<span class="ln"> 8</span><span class="n">test_set</span> <span class="o">=</span> <span class="nf">setdiff</span><span class="p">(</span><span class="n">task_swiss</span><span class="o">$</span><span class="n">row_ids</span><span class="p">,</span> <span class="n">train_set</span><span class="p">)</span>
<span class="ln"> 9</span>
<span class="ln">10</span><span class="c1"># verificando</span>
<span class="ln">11</span><span class="nf">head</span><span class="p">(</span><span class="n">train_set</span><span class="p">)</span></code></pre></div>
<pre><code>## [1]  4 39  1 34 23 14</code></pre>
<p>Com os índices selecionados, podemos realizar nosso treino apenas nos 70% escolhidos aleatoriamente da amostra, sem copiar os dados e alocar memória desnecessariamente:</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln">1</span><span class="c1"># treino</span>
<span class="ln">2</span><span class="n">l_xgboost</span><span class="o">$</span><span class="nf">train</span><span class="p">(</span><span class="n">task_swiss</span><span class="p">,</span> <span class="n">row_ids</span> <span class="o">=</span> <span class="n">train_set</span><span class="p">)</span>
<span class="ln">3</span>
<span class="ln">4</span><span class="c1"># verificando</span>
<span class="ln">5</span><span class="n">l_xgboost</span><span class="o">$</span><span class="n">model</span></code></pre></div>
<pre><code>## [10:21:01] WARNING: amalgamation/../src/objective/regression_obj.cu:171: reg:linear is now deprecated in favor of reg:squarederror.
## [1]  train-rmse:17.686886 
## Will train until train_rmse hasn&#39;t improved in 10 rounds.
## 
## [2]  train-rmse:16.014399 
## [3]  train-rmse:14.506416 
## [4]  train-rmse:13.147319 
## [5]  train-rmse:11.924172 
## [6]  train-rmse:10.822335 
## [7]  train-rmse:9.832130 
## [8]  train-rmse:8.940679 
## [9]  train-rmse:8.136598 
## [10] train-rmse:7.413037 
## [11] train-rmse:6.760063 
## [12] train-rmse:6.173677 
## [13] train-rmse:5.647888 
## [14] train-rmse:5.177068 
## [15] train-rmse:4.751254 
## [16] train-rmse:4.367561 
## [17] train-rmse:4.022047 
## [18] train-rmse:3.705540 
## [19] train-rmse:3.421478 
## [20] train-rmse:3.165364 
## [21] train-rmse:2.923110 
## [22] train-rmse:2.709535 
## [23] train-rmse:2.511684 
## [24] train-rmse:2.330560 
## [25] train-rmse:2.162180 
## [26] train-rmse:2.002988 
## [27] train-rmse:1.861695 
## [28] train-rmse:1.730979 
## [29] train-rmse:1.614930 
## [30] train-rmse:1.510077 
## [31] train-rmse:1.405107 
## [32] train-rmse:1.316820 
## [33] train-rmse:1.227179 
## [34] train-rmse:1.148336 
## [35] train-rmse:1.074920 
## [36] train-rmse:1.004666 
## [37] train-rmse:0.940519 
## [38] train-rmse:0.886334 
## [39] train-rmse:0.832195 
## [40] train-rmse:0.782907 
## [41] train-rmse:0.737985 
## [42] train-rmse:0.695803 
## [43] train-rmse:0.658468 
## [44] train-rmse:0.620991 
## [45] train-rmse:0.584939 
## [46] train-rmse:0.551442 
## [47] train-rmse:0.520346 
## [48] train-rmse:0.491411 
## [49] train-rmse:0.464267 
## [50] train-rmse:0.438681 
## [51] train-rmse:0.414958 
## [52] train-rmse:0.391905 
## [53] train-rmse:0.369801 
## [54] train-rmse:0.350035 
## [55] train-rmse:0.330991 
## [56] train-rmse:0.313710 
## [57] train-rmse:0.296662 
## [58] train-rmse:0.280962 
## [59] train-rmse:0.266252 
## [60] train-rmse:0.253146 
## [61] train-rmse:0.240702 
## [62] train-rmse:0.229117 
## [63] train-rmse:0.217732 
## [64] train-rmse:0.205889 
## [65] train-rmse:0.195538 
## [66] train-rmse:0.186375 
## [67] train-rmse:0.176608 
## [68] train-rmse:0.168004 
## [69] train-rmse:0.160256 
## [70] train-rmse:0.151921 
## [71] train-rmse:0.144080 
## [72] train-rmse:0.136428 
## [73] train-rmse:0.130172 
## [74] train-rmse:0.123807 
## [75] train-rmse:0.117861 
## [76] train-rmse:0.112243 
## [77] train-rmse:0.106818 
## [78] train-rmse:0.101794 
## [79] train-rmse:0.096382 
## [80] train-rmse:0.091913 
## [81] train-rmse:0.087061 
## [82] train-rmse:0.082908 
## [83] train-rmse:0.079150 
## [84] train-rmse:0.075045 
## [85] train-rmse:0.071658 
## [86] train-rmse:0.067890 
## [87] train-rmse:0.064352 
## [88] train-rmse:0.061335 
## [89] train-rmse:0.058158 
## [90] train-rmse:0.055464 
## [91] train-rmse:0.052609 
## [92] train-rmse:0.049872 
## [93] train-rmse:0.047326 
## [94] train-rmse:0.045157 
## [95] train-rmse:0.042823 
## [96] train-rmse:0.040716 
## [97] train-rmse:0.038909 
## [98] train-rmse:0.036942 
## [99] train-rmse:0.035096 
## [100]    train-rmse:0.033438</code></pre>
<pre><code>## ##### xgb.Booster
## raw: 156.2 Kb 
## call:
##   xgboost::xgb.train(data = data, nrounds = 100L, watchlist = list(
##     train = &lt;pointer: 0x000000001ca3f8a0&gt;), early_stopping_rounds = 10L, 
##     eta = 0.1, max_depth = 5L, objective = &quot;reg:linear&quot;)
## params (as set within xgb.train):
##   eta = &quot;0.1&quot;, max_depth = &quot;5&quot;, objective = &quot;reg:linear&quot;, validate_parameters = &quot;TRUE&quot;
## xgb.attributes:
##   best_iteration, best_msg, best_ntreelimit, best_score, niter
## callbacks:
##   cb.print.evaluation(period = print_every_n)
##   cb.evaluation.log()
##   cb.early.stop(stopping_rounds = early_stopping_rounds, maximize = maximize, 
##     verbose = verbose)
## # of features: 5 
## niter: 100
## best_iteration : 100 
## best_ntreelimit : 100 
## best_score : 0.033438 
## best_msg : [100] train-rmse:0.033438 
## nfeatures : 5 
## evaluation_log:
##     iter train_rmse
##        1  17.686886
##        2  16.014399
## ---                
##       99   0.035096
##      100   0.033438</code></pre>
<p>Como podemos ver, na primeira iteração o modelo obteve <em>rmse</em><a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a>. de 17.7, o que é alto considerando a escala [1-100] da mortalidade infantil. Ao longo do treino, o erro foi reduzido até 0.03, o que não significa que sua performance permaneça nesse nível quando extrapolado para a amostra teste ou novos dados, mas é um bom sinal. O esperado é que a performance real do modelo, após ser aplicado à amostra teste, fique entre a iteração inicial e final. Se ficar <em>melhor</em> do que a performance do teste, alguma coisa certamente está errada.</p>
<p>Vamos verificar qual a performance real após realizarmos as predições na amostra teste. Primeiro, passamos os índices de teste ao objeto do <em>learner</em> com o modelo e chamamos o método <code>predict()</code> para obter as predições.</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln">1</span><span class="c1"># predições</span>
<span class="ln">2</span><span class="n">preds</span> <span class="o">=</span> <span class="n">l_xgboost</span><span class="o">$</span><span class="nf">predict</span><span class="p">(</span><span class="n">task_swiss</span><span class="p">,</span> <span class="n">row_ids</span> <span class="o">=</span> <span class="n">test_set</span><span class="p">)</span>
<span class="ln">3</span>
<span class="ln">4</span><span class="c1"># verificando</span>
<span class="ln">5</span><span class="n">preds</span></code></pre></div>
<pre><code>## &lt;PredictionRegr&gt; for 15 observations:
##     row_ids truth response
##           8  24.9 20.69299
##          11  24.5 20.65381
##          13  19.1 15.63718
## ---                       
##          40  20.5 19.55373
##          43  20.0 21.27585
##          47  19.3 21.82050</code></pre>
<p>No objeto com as predições, são armazenados tanto os valores preditos pelo modelo <code>response</code> quanto os valores da amostra <code>truth</code>. Esses valores então podem ser comparados para calcular a acurácia do modelo através do método <code>score()</code>:</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln">1</span><span class="c1"># acurácia</span>
<span class="ln">2</span><span class="n">preds</span><span class="o">$</span><span class="nf">score</span><span class="p">(</span><span class="nf">list</span><span class="p">(</span>
<span class="ln">3</span>  <span class="nf">msr</span><span class="p">(</span><span class="s">&#34;regr.rmse&#34;</span><span class="p">),</span>
<span class="ln">4</span>  <span class="nf">msr</span><span class="p">(</span><span class="s">&#34;regr.mae&#34;</span><span class="p">)</span>
<span class="ln">5</span><span class="p">))</span>
<span class="ln">6</span>
<span class="ln">7</span><span class="c1"># visualizando</span>
<span class="ln">8</span><span class="nf">autoplot</span><span class="p">(</span><span class="n">preds</span><span class="p">)</span></code></pre></div>
<pre><code>## regr.rmse  regr.mae 
##  2.587082  2.214177</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="https://botam2.github.io/workshop/post/2020-11-29-introducao-ao-mlr3-framework/index_files/figure-html/accuracy-1.png" width="672" /></p>
<p>A <em>rmse</em> do modelo na amostra teste ficou em apenas 2.59 unidades, o que é uma performance muito boa!</p>
</div>
<div id="interpretação" class="section level1">
<h1>INTERPRETAÇÃO</h1>
<p>Como o XGBoost possui a propriedade de <em>feature importance</em>, podemos extraí-la com o método <code>importance()</code>:</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-r" data-lang="r"><span class="ln">1</span><span class="c1"># feature importance</span>
<span class="ln">2</span><span class="n">l_xgboost</span><span class="o">$</span><span class="nf">importance</span><span class="p">()</span>
<span class="ln">3</span>
<span class="ln">4</span><span class="c1"># visualizando</span>
<span class="ln">5</span><span class="nf">barplot</span><span class="p">(</span><span class="n">l_xgboost</span><span class="o">$</span><span class="nf">importance</span><span class="p">())</span></code></pre></div>
<pre><code>##    Catholic Agriculture   Fertility Examination   Education 
##  0.39696784  0.24723198  0.20219343  0.10340228  0.05020448</code></pre>
<p><img src="https://botam2.github.io/workshop/post/2020-11-29-introducao-ao-mlr3-framework/index_files/figure-html/importance-1.png" width="672" /></p>
<p>Entretanto, somente a importância não nos descreve o relacionamento da <em>feature</em> com a variável de resposta, nem mesmo sua direção, sendo uma medida muito pobre de interpretação. Discutiremos técnicas de interpretação em outras postagens.</p>
</div>
<div id="citação" class="section level1">
<h1>CITAÇÃO</h1>
<p>Para citar esse post, use:

<p>Alberson Miranda. Dec 27, 2020. <em>"Introdução ao framework {mlr3}"</em>. https://botam2.github.io/workshop/post/2020-11-29-introducao-ao-mlr3-framework/.</p>

<p>Ou a entrada em BibTex:</p>

<code><pre>
  @misc&#123;datamares,
    title = {Introdução ao framework {mlr3}},
    author = {Alberson Miranda},
    year = {2020},
    url = {https://botam2.github.io/workshop/post/2020-11-29-introducao-ao-mlr3-framework/}
  &#125;
</pre></code></p>
</div>
<div id="referências" class="section level1 unnumbered">
<h1>REFERÊNCIAS</h1>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-R-R6" class="csl-entry">
Chang, Winston. 2020. <em>R6: Encapsulated Classes with Reference Semantics</em>. <a href="https://CRAN.R-project.org/package=R6">https://CRAN.R-project.org/package=R6</a>.
</div>
<div id="ref-xgboost" class="csl-entry">
Chen, Tianqi, Tong He, Michael Benesty, Vadim Khotilovich, Yuan Tang, Hyunsu Cho, Kailong Chen, et al. 2020. <em>Xgboost: Extreme Gradient Boosting</em>. <a href="https://CRAN.R-project.org/package=xgboost">https://CRAN.R-project.org/package=xgboost</a>.
</div>
<div id="ref-R-data.table" class="csl-entry">
Dowle, Matt, and Arun Srinivasan. 2020. <em>Data.table: Extension of ‘Data.frame‘</em>. <a href="https://CRAN.R-project.org/package=data.table">https://CRAN.R-project.org/package=data.table</a>.
</div>
<div id="ref-mlr3" class="csl-entry">
Lang, Michel, Martin Binder, Jakob Richter, Patrick Schratz, Florian Pfisterer, Stefan Coors, Quay Au, Giuseppe Casalicchio, Lars Kotthoff, and Bernd Bischl. 2019. <span>“<span class="nocase">mlr3</span>: A Modern Object-Oriented Machine Learning Framework in <span>R</span>.”</span> <em>Journal of Open Source Software</em>, December. <a href="https://doi.org/10.21105/joss.01903">https://doi.org/10.21105/joss.01903</a>.
</div>
<div id="ref-R" class="csl-entry">
R Core Team. 2020. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>No {mlr3} é chamado de <em>learner</em>.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Também chamada de <em>output feature</em> ou <em>label</em>.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>Aqui trabalharemos apenas com um, mas em posts futuros utilizaremos de diversas formas — pipelines com diferentes <em>features</em>, <em>stacking</em> etc.<a href="#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>Raiz do Erro Médio Quadrático<a href="#fnref4" class="footnote-back">↩︎</a></p></li>
</ol>
</div>


  </article>
<aside class="sidebar">
  <section class="sidebar_inner">
        <h2>Alberson Miranda</h2>
      <div class="author_bio">
        coordenador no @Banestes_SA, economista (UFES) e graduando em matemática (IFES). #rstats &amp; #python.
      </div>
      <a href='https://botam2.github.io/workshop/about/' class="button mt-1" role="button" title='Read More'>Read More</a>
    <h2 class="mt-4">Recent Posts</h2>
    <ul class="flex-column">
      <li>
        <a href="https://botam2.github.io/workshop/post/configurando-git-em-um-servidor-proxy/" class="nav-link" title="Configurando git em um servidor proxy">Configurando git em um servidor proxy</a>
      </li>
      <li>
        <a href="https://botam2.github.io/workshop/post/hello-world/" class="nav-link" title="Hello World!">Hello World!</a>
      </li>
    </ul>
    <div>
      <h2 class="mt-4 taxonomy" id="tags-section">Tags</h2>
      <nav class="tags_nav">
        <a href='https://botam2.github.io/workshop/tags/eu/' class="post_tag button button_translucent" title="eu">
          EU
          <span class="button_tally">1</span>
        </a>
        
        <a href='https://botam2.github.io/workshop/tags/git/' class="post_tag button button_translucent" title="git">
          GIT
          <span class="button_tally">1</span>
        </a>
        
        <a href='https://botam2.github.io/workshop/tags/index/' class="post_tag button button_translucent" title="index">
          INDEX
          <span class="button_tally">1</span>
        </a>
        
        <a href='https://botam2.github.io/workshop/tags/mlr3/' class="post_tag button button_translucent" title="mlr3">
          MLR3
          <span class="button_tally">1</span>
        </a>
        
        <a href='https://botam2.github.io/workshop/tags/r/' class="post_tag button button_translucent" title="r">
          R
          <span class="button_tally">1</span>
        </a>
        
        <a href='https://botam2.github.io/workshop/tags/usethis/' class="post_tag button button_translucent" title="usethis">
          USETHIS
          <span class="button_tally">1</span>
        </a>
        
        
      </nav>
    </div>
  </section>
</aside>

  
</div>
    </main><svg width="0" height="0" class="hidden">
  <symbol viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" id="facebook">
    <path d="M437 0H75C33.648 0 0 33.648 0 75v362c0 41.352 33.648 75 75 75h151V331h-60v-90h60v-61c0-49.629 40.371-90 90-90h91v90h-91v61h91l-15 90h-76v181h121c41.352 0 75-33.648 75-75V75c0-41.352-33.648-75-75-75zm0 0"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18.001 18.001" id="twitter">
    <path d="M15.891 4.013c.808-.496 1.343-1.173 1.605-2.034a8.68 8.68 0 0 1-2.351.861c-.703-.756-1.593-1.14-2.66-1.14-1.043 0-1.924.366-2.643 1.078a3.56 3.56 0 0 0-1.076 2.605c0 .309.039.585.117.819-3.076-.105-5.622-1.381-7.628-3.837-.34.601-.51 1.213-.51 1.846 0 1.301.549 2.332 1.645 3.089-.625-.053-1.176-.211-1.645-.47 0 .929.273 1.705.82 2.388a3.623 3.623 0 0 0 2.115 1.291c-.312.08-.641.118-.979.118-.312 0-.533-.026-.664-.083.23.757.664 1.371 1.291 1.841a3.652 3.652 0 0 0 2.152.743C4.148 14.173 2.625 14.69.902 14.69c-.422 0-.721-.006-.902-.038 1.697 1.102 3.586 1.649 5.676 1.649 2.139 0 4.029-.542 5.674-1.626 1.645-1.078 2.859-2.408 3.639-3.974a10.77 10.77 0 0 0 1.172-4.892v-.468a7.788 7.788 0 0 0 1.84-1.921 8.142 8.142 0 0 1-2.11.593z"
      ></path>
  </symbol>
  <symbol aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" id="mail">
    <path  d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" id="calendar">
    <path d="M452 40h-24V0h-40v40H124V0H84v40H60C26.916 40 0 66.916 0 100v352c0 33.084 26.916 60 60 60h392c33.084 0 60-26.916 60-60V100c0-33.084-26.916-60-60-60zm20 412c0 11.028-8.972 20-20 20H60c-11.028 0-20-8.972-20-20V188h432v264zm0-304H40v-48c0-11.028 8.972-20 20-20h24v40h40V80h264v40h40V80h24c11.028 0 20 8.972 20 20v48z"></path>
    <path d="M76 230h40v40H76zm80 0h40v40h-40zm80 0h40v40h-40zm80 0h40v40h-40zm80 0h40v40h-40zM76 310h40v40H76zm80 0h40v40h-40zm80 0h40v40h-40zm80 0h40v40h-40zM76 390h40v40H76zm80 0h40v40h-40zm80 0h40v40h-40zm80 0h40v40h-40zm80-80h40v40h-40z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" id="github">
    <path d="M255.968 5.329C114.624 5.329 0 120.401 0 262.353c0 113.536 73.344 209.856 175.104 243.872 12.8 2.368 17.472-5.568 17.472-12.384 0-6.112-.224-22.272-.352-43.712-71.2 15.52-86.24-34.464-86.24-34.464-11.616-29.696-28.416-37.6-28.416-37.6-23.264-15.936 1.728-15.616 1.728-15.616 25.696 1.824 39.2 26.496 39.2 26.496 22.848 39.264 59.936 27.936 74.528 21.344 2.304-16.608 8.928-27.936 16.256-34.368-56.832-6.496-116.608-28.544-116.608-127.008 0-28.064 9.984-51.008 26.368-68.992-2.656-6.496-11.424-32.64 2.496-68 0 0 21.504-6.912 70.4 26.336 20.416-5.696 42.304-8.544 64.096-8.64 21.728.128 43.648 2.944 64.096 8.672 48.864-33.248 70.336-26.336 70.336-26.336 13.952 35.392 5.184 61.504 2.56 68 16.416 17.984 26.304 40.928 26.304 68.992 0 98.72-59.84 120.448-116.864 126.816 9.184 7.936 17.376 23.616 17.376 47.584 0 34.368-.32 62.08-.32 70.496 0 6.88 4.608 14.88 17.6 12.352C438.72 472.145 512 375.857 512 262.353 512 120.401 397.376 5.329 255.968 5.329z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 212 212" id="gitlab">
    <path d="M12.3 74.7h54L43.3 3c-1-3.6-6.4-3.6-7.6 0L12.3 74.8z" />
    <path d="M12.3 74.7L.5 111c-1 3.2 0 6.8 3 8.8l101.6 74-92.5-119z"/>
    <path d="M105 193.7l-38.6-119h-54l92.7 119z"/>
    <path d="M105 193.7l38.7-119H66.4l38.7 119z"/>
    <path d="M105 193.7l38.7-119H198l-93 119z"/>
    <path d="M198 74.7l11.6 36.2c1 3 0 6.6-3 8.6l-101.5 74 93-119z"/>
    <path d="M198 74.7h-54.3L167 3c1.2-3.6 6.4-3.6 7.6 0L198 74.8z"/> 
  </symbol>
  <symbol viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" id="rss">
    <circle cx="3.429" cy="20.571" r="3.429"></circle>
    <path d="M11.429 24h4.57C15.999 15.179 8.821 8.001 0 8v4.572c6.302.001 11.429 5.126 11.429 11.428z"></path>
    <path d="M24 24C24 10.766 13.234 0 0 0v4.571c10.714 0 19.43 8.714 19.43 19.429z"></path>
  </symbol>
  <symbol viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" id="linkedin">
    <path d="M437 0H75C33.648 0 0 33.648 0 75v362c0 41.352 33.648 75 75 75h362c41.352 0 75-33.648 75-75V75c0-41.352-33.648-75-75-75zM181 406h-60V196h60zm0-240h-60v-60h60zm210 240h-60V286c0-16.54-13.46-30-30-30s-30 13.46-30 30v120h-60V196h60v11.309C286.719 202.422 296.93 196 316 196c40.691.043 75 36.547 75 79.688zm0 0"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 612 612" id="arrow">
    <path d="M604.501 440.509L325.398 134.956c-5.331-5.357-12.423-7.627-19.386-7.27-6.989-.357-14.056 1.913-19.387 7.27L7.499 440.509c-9.999 10.024-9.999 26.298 0 36.323s26.223 10.024 36.222 0l262.293-287.164L568.28 476.832c9.999 10.024 26.222 10.024 36.221 0 9.999-10.023 9.999-26.298 0-36.323z"></path>
  </symbol>
  <symbol viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" id="carly">
    <path d="M504.971 239.029L448 182.059V84c0-46.317-37.682-84-84-84h-44c-13.255 0-24 10.745-24 24s10.745 24 24 24h44c19.851 0 36 16.149 36 36v108c0 6.365 2.529 12.47 7.029 16.971L454.059 256l-47.029 47.029A24.002 24.002 0 0 0 400 320v108c0 19.851-16.149 36-36 36h-44c-13.255 0-24 10.745-24 24s10.745 24 24 24h44c46.318 0 84-37.683 84-84v-98.059l56.971-56.971c9.372-9.372 9.372-24.568 0-33.941zM112 192V84c0-19.851 16.149-36 36-36h44c13.255 0 24-10.745 24-24S205.255 0 192 0h-44c-46.318 0-84 37.683-84 84v98.059l-56.971 56.97c-9.373 9.373-9.373 24.568 0 33.941L64 329.941V428c0 46.317 37.682 84 84 84h44c13.255 0 24-10.745 24-24s-10.745-24-24-24h-44c-19.851 0-36-16.149-36-36V320c0-6.365-2.529-12.47-7.029-16.971L57.941 256l47.029-47.029A24.002 24.002 0 0 0 112 192z"></path>
  </symbol>
  <symbol viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" id="copy">
    <path d="M23 2.75A2.75 2.75 0 0 0 20.25 0H8.75A2.75 2.75 0 0 0 6 2.75v13.5A2.75 2.75 0 0 0 8.75 19h11.5A2.75 2.75 0 0 0 23 16.25zM18.25 14.5h-7.5a.75.75 0 0 1 0-1.5h7.5a.75.75 0 0 1 0 1.5zm0-3h-7.5a.75.75 0 0 1 0-1.5h7.5a.75.75 0 0 1 0 1.5zm0-3h-7.5a.75.75 0 0 1 0-1.5h7.5a.75.75 0 0 1 0 1.5z"></path>
    <path d="M8.75 20.5a4.255 4.255 0 0 1-4.25-4.25V2.75c0-.086.02-.166.025-.25H3.75A2.752 2.752 0 0 0 1 5.25v16A2.752 2.752 0 0 0 3.75 24h12a2.752 2.752 0 0 0 2.75-2.75v-.75z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512.001 512.001" id="closeme">
    <path d="M284.286 256.002L506.143 34.144c7.811-7.811 7.811-20.475 0-28.285-7.811-7.81-20.475-7.811-28.285 0L256 227.717 34.143 5.859c-7.811-7.811-20.475-7.811-28.285 0-7.81 7.811-7.811 20.475 0 28.285l221.857 221.857L5.858 477.859c-7.811 7.811-7.811 20.475 0 28.285a19.938 19.938 0 0 0 14.143 5.857 19.94 19.94 0 0 0 14.143-5.857L256 284.287l221.857 221.857c3.905 3.905 9.024 5.857 14.143 5.857s10.237-1.952 14.143-5.857c7.811-7.811 7.811-20.475 0-28.285L284.286 256.002z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" id="open-menu">
    <path d="M492 236H20c-11.046 0-20 8.954-20 20s8.954 20 20 20h472c11.046 0 20-8.954 20-20s-8.954-20-20-20zm0-160H20C8.954 76 0 84.954 0 96s8.954 20 20 20h472c11.046 0 20-8.954 20-20s-8.954-20-20-20zm0 320H20c-11.046 0-20 8.954-20 20s8.954 20 20 20h472c11.046 0 20-8.954 20-20s-8.954-20-20-20z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="instagram">
    <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id=youtube>
    <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"/>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="stackoverflow">
    <path d="M21 27v-8h3v11H0V19h3v8h18z"></path><path d="M17.1.2L15 1.8l7.9 10.6 2.1-1.6L17.1.2zm3.7 14.7L10.6 6.4l1.7-2 10.2 8.5-1.7 2zM7.2 12.3l12 5.6 1.1-2.4-12-5.6-1.1 2.4zm-1.8 6.8l13.56 1.96.17-2.38-13.26-2.55-.47 2.97zM19 25H5v-3h14v3z"></path>
  </symbol>
</svg>


  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js" integrity="sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>
<footer class="footer">
  <div class="footer_inner wrap pale">
    <img src='https://botam2.github.io/workshop/icons/apple-touch-icon.png' class="icon icon_2 transparent" alt="Datamares &amp; Dreamscapes">
    <p>Copyright&nbsp;2020-&nbsp;<span class="year"></span>&nbsp;DATAMARES &amp; DREAMSCAPES. All Rights Reserved</p><a class="to_top" href="#documentTop">
  <svg class="icon">
  <use xlink:href="#arrow"></use>
</svg>
</a>

  </div>
</footer>

    <script type="text/javascript" src="https://botam2.github.io/workshop/js/bundle.min.d14fbcd65c3ba32e60cab81f8bbe7aa9b7f8b95ff8290e437fb26ff9ab7f7ea0c928db2dca60aac91f192db906f2d90678f83907e4e3994f6ff9fdb5bdea3369.js" integrity="sha512-0U&#43;81lw7oy5gyrgfi756qbf4uV/4KQ5Df7Jv&#43;at/fqDJKNstymCqyR8ZLbkG8tkGePg5B&#43;TjmU9v&#43;f21veozaQ==" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Merriweather&family=Inconsolata&family=IBM+Plex+Mono&family=Nunito&family=Fira+Code&family=Source+Code+Pro&family=Montserrat&family=Raleway&family=Roboto" rel="stylesheet">

  </body>
</html>
